spring:
  datasource:
    url: jdbc:mysql://36.41.187.107:3306/financial_manager?user=root&password=Ywm@mysql36&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081